In [2]:
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from sklearn.datasets import load_wine
from sklearn.metrics.cluster import contingency_matrix
from sklearn.metrics import silhouette_score
from sklearn.metrics import f1_score

In [3]:
wine = load_wine()

In [4]:
D_wine = wine.data

In [5]:
target = wine.target

In [10]:
ac = AgglomerativeClustering (n_clusters= 6, metric= 'euclidean', linkage= 'single')

In [11]:
ac.fit(D_wine)

AgglomerativeClustering(linkage='single', metric='euclidean', n_clusters=6)

In [12]:
ac.labels_

array([0, 0, 0, 5, 2, 5, 0, 0, 0, 0, 5, 0, 0, 0, 5, 0, 0, 0, 3, 2, 2, 2,
       0, 0, 2, 2, 0, 0, 2, 0, 0, 5, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [13]:
contingency_matrix(ac.labels_, target)

array([[39,  1,  0],
       [ 0,  1,  0],
       [13, 69, 48],
       [ 1,  0,  0],
       [ 1,  0,  0],
       [ 5,  0,  0]])

In [15]:
silhouette_score(D_wine, ac.labels_)

0.28405280556794804

In [16]:
f1_score(target, ac.labels_, average= 'weighted')

0.4176669166096006

In [17]:
ac = AgglomerativeClustering (n_clusters= 3, metric= 'euclidean', linkage= 'single')

In [18]:
ac.fit(D_wine)

AgglomerativeClustering(linkage='single', metric='euclidean', n_clusters=3)

In [19]:
ac.labels_

array([0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [20]:
contingency_matrix(ac.labels_, target)

array([[53, 71, 48],
       [ 1,  0,  0],
       [ 5,  0,  0]])

In [21]:
silhouette_score(D_wine, ac.labels_)

0.48798203351890634

In [22]:
f1_score(target, ac.labels_, average= 'weighted')

0.15209883749209593

In [23]:
ac = AgglomerativeClustering (n_clusters= 3, metric= 'euclidean', linkage= 'complete')

In [24]:
ac.fit(D_wine)

AgglomerativeClustering(linkage='complete', metric='euclidean', n_clusters=3)

In [25]:
ac.labels_

array([0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2,
       2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2,
       2, 1])

In [26]:
contingency_matrix(ac.labels_, target)

array([[43,  0,  0],
       [ 0, 56, 27],
       [16, 15, 21]])

In [27]:
silhouette_score(D_wine, ac.labels_)

0.5418973703348594

In [28]:
f1_score(target, ac.labels_, average= 'weighted')

0.6828172004246029

In [29]:
ac = AgglomerativeClustering (n_clusters= 3, metric= 'euclidean', linkage= 'ward')

In [30]:
ac.fit(D_wine)

AgglomerativeClustering(metric='euclidean', n_clusters=3)

In [31]:
ac.labels_

array([0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 0, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1])

In [32]:
contingency_matrix(ac.labels_, target)

array([[46,  2,  0],
       [ 0, 51, 21],
       [13, 18, 27]])

In [33]:
silhouette_score(D_wine, ac.labels_)

0.5644796401732068

In [34]:
f1_score(target, ac.labels_, average= 'weighted')

0.7068829145767007